stages:
  - test

py27:
  image: python:2.7
  stage: test
  script:
    - pip install tox
    - pip install ansible
    - tox -e 'py27-{pytest_oldest,pytest_latest}'

py36:
  image: python:3.6
  stage: test
  script:
    - pip install tox
    - pip install ansible
    - tox -e 'py36-{pytest_oldest,pytest_latest}'

flake8:
  image: python:3.6
  stage: test
  script:
    - pip install tox
    - tox -e flake8
